### ISSUE TITLE
Version 2.6 Release

### ISSUE THREAD

**Issue by vheuken** [thibaudgg/video_info#103]
I'm going to spend some time soon handling the latest batch of issues so we can release version 2.6.

The tasks at hand:
- [x] [Implement Vimeo scraper](https://github.com/thibaudgg/video_info/issues/95)
- [x] [Convert Networking errors into custom exceptions](https://github.com/thibaudgg/video_info/issues/62)
- [x] [400 Bad Request error suppressed when invalid API key is provided](https://github.com/thibaudgg/video_info/issues/86) 
- [x] [Pin all dependencies](https://github.com/thibaudgg/video_info/issues/104)
- [x] Finish PR #65 
- [x] #114 

I'd like to do get #83 in as well, but I won't personally spend time on it (at least, not for this release). If someone else (@robguilfoyle?) wants to finish it, that'd be great.

**Comment by vheuken** [comment]
Looks like all that is left is the Vimeo scraper. I'll work on that soon!

**Comment by maia** [comment]
@vheuken, is there any news on the release schedule of version 2.6? In case it needs some more time, how about moving the vimeo scraper to 2.7 and releasing the status quo as 2.6?

**Comment by vheuken** [comment]
@maia I'll be making time for it tonight. Sorry for the delay.

**Comment by vheuken** [comment]
if you guys want status on the Vimeo scraper, see: https://github.com/thibaudgg/video_info/issues/95#issuecomment-160628927

**Comment by vheuken** [comment]
I added #114 in. Should be pretty quick

**Comment by vheuken** [comment]
@thibaudgg We're ready for the 2.6 release!

**Comment by thibaudgg** [comment]
Just released 2.6, thanks for your great work @vheuken!
